### PR TITLE
Proposal: Decouple language support from FaaS drivers

### PR DESCRIPTION
**Pull request by imikushin**
The spec for #269

### CODE REVIEW

**Comment by kars7e** [comment]
One more thing came to my mind. This proposal doesn't address the runtime dependencies feature. Today, when creating an image, a user can specify runtime dependencies, which are language-dependent. This is implemented in image manager, and if a new language is added, it would also require implementation there.

**Comment by berndtj** [comment]
How will this work with non JSON payloads?

I think it's worth pointing out that I don't think the point of this is to allow the users/adminstrators of a dispatch installation to add language support, but it's more for us to add languages to existing installations by updating/adding to the base-images. At least that's how I read it.

@kars7e makes a good point, can we pull in the dependency related code into the image some how?  Otherwise we still need to rebuild when supporting a new language.

**Comment by imikushin** [comment]
Thanks for comments! 

If the admin is adding a language runtime image (or "base-image"), they are expected to be able to install the Function Runtime API implementation for that language into the image. We're going to provide examples for that (for JS, Python and PowerShell - at least).

**Comment by imikushin** [comment]
@kars7e I'll add the runtime dependency manifest support - great catch!

**Comment by berndtj** [comment]
I understand this is to allow Dispatch more language flexibility.  I'm just stating that there is still some overhead to supporting a language (it's just all contained in the base image itself now).  This could of course come from a dispatch administrator, but would likely come from us.  Regardless we need to document it well!

**Comment by imikushin** [comment]
This is now obsolete as #339 already implemented the feature. Closing in favor of upcoming documentation update.

**Pull request closed without merging**
