### PR TITLE
Bump dispatch chart version

### PR DESCRIPTION
**Pull request by neosab**
After the changes to the chart in #147 the version needs a bump.

### CODE REVIEW

**Comment by neosab** [comment]
Not needed. It's already updated

**Comment by neosab** [comment]
My bad I thought this was updated. Reopening..

**Comment by berndtj** [comment]
So, I think we do want to bump the chart version after all, just in case folks don't use the install command.  Also, we need to update the image number in the charts/dispatch/values.yaml file.

**Comment by berndtj** [comment]
I'm closing this as we should just bump the version next time we make changes to the charts.  We kind of missed the boat on this one

**Pull request closed without merging**
